class ApiError extends Error {
  constructor(statusCode, code, message, extra = {}) {
    super(message);
    this.statusCode = statusCode;
    this.code = code;
    this.extra = extra;
  }
}

const Codes = {
  INVALID_REFERRAL_CODE: 'INVALID_REFERRAL_CODE',
  REFERRAL_ALREADY_ASSIGNED: 'REFERRAL_ALREADY_ASSIGNED',
  SELF_REFERRAL_DETECTED: 'SELF_REFERRAL_DETECTED',
  DEVICE_ALREADY_ASSOCIATED: 'DEVICE_ALREADY_ASSOCIATED',
  REFERRAL_NOT_ELIGIBLE: 'REFERRAL_NOT_ELIGIBLE',
  REWARD_ALREADY_CREDITED: 'REWARD_ALREADY_CREDITED',
  RATE_LIMITED: 'RATE_LIMITED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  FRAUD_REVIEW: 'FRAUD_REVIEW',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = { ApiError, Codes };
